version: "3.1"


services:

# MariaDB container
  database:
    image: mysql
    container_name: mariadb_container
    environment:
        - MYSQL_ROOT_PASSWORD=root
    links:
        - server   
    ports:
       - "33061:3306"
       
# phpMyAdmin container
  server:
    build: .
    container_name: server_container
    ports:
       - "8081:80"
    volumes: 
       - .:/var/www/html