version: "3.1"
services:

# MariaDB container
  mariadb:
    image: mariadb
    container_name: mariadb_container
    environment:
        - MYSQL_ROOT_PASSWORD=root
        
  
# apache-server container
  apache-server:
    #/ A CHANGER PAR LA LIGNE SUIVANTE !
    build: .
    image: php:apachePDO
    container_name: apache-server
    ports:
      - "8080:80"
    links:
        - mariadb:db
    volumes: 
       - .:/var/www/html
